
baseURL = "http://examplesite.org"
title = "VNA | "
theme = "vna-sandbox"
paginate = "6"
summaryLength = "10"
disqusShortname = "vna"
disableLanguages = []
defaultContentLanguage = "pt"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "course"
URL = "course"
weight = 2

[[menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[menu.main]]
  parent = "Pages"
  name = "teacher"
  URL = "teacher"

  [[menu.main]]
  parent = "Pages"
  name = "notice"
  URL = "notice"

  [[menu.main]]
  parent = "Pages"
  name = "event"
  URL = "event"

  [[menu.main]]
  parent = "Pages"
  name = "scholarship"
  URL = "scholarship"

  [[menu.main]]
  parent = "Pages"
  name = "research"
  URL = "research"

[[menu.main]]
name = "blog"
URL = "blog"
weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5


[[menu.footer]]
name = "teacher"
URL = "teacher"

[[menu.footer]]
name = "notice"
URL = "notice"

[[menu.footer]]
name = "event"
URL = "event"

[[menu.footer]]
name = "scholarship"
URL = "scholarship"

[[menu.footer]]
name = "research"
URL = "research"


[params]
logo = "images/logo.png"
description = "This is meta description"
author = "Themefisher"
address = "9567 Turner Trace Apt. BC C3G8A4"
mobile = "+211234565523"
email = "info@educenter.com"
contact_form_action = "#" # contact form works with https://formspree.io
google_analitycs_id = "" # your id
top_header = true

[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

[languages]

  [languages.pt]
  languageName = "PT"
  languageCode = "pt-br"
  contentDir = "content/pt"
  weight = 1
  home = "Inicio"

  [languages.en]
  languageName = "EN"
  languageCode = "en-us"
  contentDir = "content/en"
  weight = 2
  home = "Home"

  [languages.fr]
  languageName = "FR"
  languageCode = "fr-fr"
  contentDir = "content/fr"
  weight = 3
  home = "Accueil"

  [languages.es]
  languageName = "ES"
  languageCode = "es-es"
  contentDir = "content/es"
  weight = 4
  home = "Inicio"
